# Generated by Django 5.2.3 on 2025-07-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.CharField(default='default', max_length=40),
            preserve_default=False,
        ),
    ]
